version: "3.7"

services:
    web:
        image: nginx:alpine
        container_name: nginx
        restart: always
        tty: true
        volumes:
            - ${ROOT}:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:delegated
        ports:
            - "${NGINX_PORT}:80"
            - "${NGINX_SSL_PORT}:443"
        depends_on:
            - app
            - db
        networks:
            - app-network

    app:
        image: php:7.2-fpm-alpine
        container_name: php
        restart: always
        tty: true
        build:
            context: ./php
            dockerfile: Dockerfile
        ports:
            - "${PHP_PORT}:9000"
        environment:
            - XDEBUG_CONFIG="xdebug.idekey=${XDEBUG_IDE_KEY}"
        volumes:
            - ${ROOT}:/var/www/html
            - ~/.composer:/var/www/.composer:delegated
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini:delegated
        networks:
            - app-network

    db:
        image: percona:5.7
        container_name: mysql
        restart: unless-stopped
        ports:
            - "${MYSQL_PORT}:3306"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql

    redis:
        image: redis:5.0.6-alpine
        container_name: redis
        ports:
            - "${REDIS_PORT}:6379"

    es01:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.4.1
        container_name: es01
        restart: always
        environment:
            - node.name=es01
            - discovery.seed_hosts=es01
            - cluster.initial_master_nodes=es01
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - esdata01:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            - esnet

    kibana:
        image: docker.elastic.co/kibana/kibana:6.5.4
        container_name: kibana
        restart: always
        environment:
            - ELASTICSEARCH_URL=http://es01:9200
        ports:
            - "${KIBANA_PORT}:5601"
        depends_on:
            - es01

networks:
    esnet:
    app-network:

volumes:
    dbdata:
    esdata01:
        driver: local
